name: OpenOSRS - CI

on: [pull_request, push]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: PR title lint
        if: github.event_name == 'pull_request'
        uses: seferov/pr-lint-action@master
        with:
          title-regex: '^\w+: \w+'

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 9, 11, 12 ]

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
      - name: Assembling
        run: gradlew assemble --console=plain
      - name: Building
        run: gradlew build --stacktrace -x test -x checkstyleMain --console=plain

  test:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 9, 11, 12 ]

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
      - name: Assembling
        run: gradlew assemble --console=plain
      - name: Testing
        run: gradlew test --stacktrace --console=plain

  checkstyle:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: 11
      - name: Assembling
        run: gradlew assemble --console=plain
      - name: Checking code conventions
        run: gradlew checkstyleMain --console=plain

  approve:
    needs: [build, test, checkstyle]
    runs-on: ubuntu-latest

    steps:
      - name: "Approve"
        if: github.event_name == 'pull_request' && github.actor == 'github-actions[bot]'
        uses: hmarr/auto-approve-action@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"